export const interests = [
  { label: "Computer Architecture" },
  { label: "Machine Learning" },
  { label: "Data Structures and Algorithms" },
  { label: "Web Development" },
  { label: "Artificial Intelligence" },
  { label: "Operating Systems" },
  { label: "Network Security" },
  { label: "Database Management Systems" },
  { label: "Cloud Computing" },
  { label: "Software Engineering" },
  { label: "Computer Graphics" },
  { label: "Cybersecurity" },
  { label: "Programming Languages" },
  { label: "Mobile App Development" },
  { label: "Data Science" },
  { label: "Computer Vision" },
  { label: "Robotics" },
  { label: "Natural Language Processing" },
  { label: "Game Development" },
  { label: "Quantum Computing" },
  { label: "Internet of Things (IoT)" },
  { label: "Embedded Systems" },
  { label: "Blockchain Technology" },
  { label: "Big Data Analytics" },
  { label: "Virtual Reality (VR)" },
  { label: "Augmented Reality (AR)" },
  { label: "Parallel Computing" },
  { label: "Bioinformatics" },
  { label: "Compiler Design" },
  { label: "Cryptography" },
  { label: "Computer Networks" },
  { label: "Distributed Systems" },
  { label: "Graph Theory" },
  { label: "Human-Computer Interaction" },
  { label: "Information Retrieval" },
  { label: "Microservices Architecture" },
  { label: "Mobile Computing" },
  { label: "Multimedia Systems" },
  { label: "Neural Networks" },
  { label: "Pattern Recognition" },
  { label: "Quantum Information Science" },
  { label: "Reinforcement Learning" },
  { label: "Simulations and Modeling" },
  { label: "Social Computing" },
  { label: "Software Testing" },
  { label: "Web Security" },
  { label: "Data Mining" },
  { label: "Evolutionary Computing" },
  { label: "Geographic Information Systems (GIS)" },
  { label: "Humanoid Robotics" },
  { label: "Information Security" },
  { label: "Internet Technologies" },
  { label: "Knowledge Representation and Reasoning" },
  { label: "Machine Translation" },
  { label: "Natural Language Understanding" },
  { label: "Object-Oriented Programming" },
  { label: "Predictive Analytics" },
  { label: "Programming Paradigms" },
  { label: "Quantum Algorithms" },
  { label: "Real-Time Systems" },
  { label: "Secure Coding" },
  { label: "Semantic Web" },
  { label: "Smart Contracts" },
  { label: "Speech Recognition" },
  { label: "Text Mining" },
  { label: "User Interface Design" },
  { label: "Web Development Frameworks" },
  { label: "Wireless Sensor Networks" },
  { label: "Algorithms for Optimization" },
  { label: "Artificial General Intelligence" },
  { label: "Automated Reasoning" },
  { label: "Cloud Security" },
  { label: "Computational Biology" },
  { label: "Computational Geometry" },
  { label: "Computational Linguistics" },
  { label: "Computational Neuroscience" },
  { label: "Computer-Aided Design (CAD)" },
  { label: "Computer Vision Systems" },
  { label: "Concurrency Control" },
  { label: "Convolutional Neural Networks" },
  { label: "Data Compression" },
  { label: "Data Privacy" },
  { label: "Digital Signal Processing" },
  { label: "Distributed Computing" },
  { label: "Genetic Algorithms" },
  { label: "Information Extraction" },
  { label: "Information Theory" },
  { label: "Knowledge Engineering" },
  { label: "Logic Programming" },
  { label: "Machine Ethics" },
  { label: "Machine Perception" },
  { label: "Memory Management" },
  { label: "Mobile Robotics" },
  { label: "Natural Language Generation" },
  { label: "Network Protocols" },
  { label: "Numerical Analysis" },
  { label: "Optical Character Recognition" },
  { label: "Parallel Algorithms" },
  { label: "Privacy-Preserving Data Mining" },
  { label: "Quantum Cryptography" },
];
